### PR TITLE
initial commit zsh completions

### PR DESCRIPTION
**Pull request by drgibbon**

### CODE REVIEW

**Comment by drgibbon** [comment]
Any chance to have these merged into a new release at some stage? :)

**Comment by chinarulezzz** [comment]
Needs to review due to this change https://github.com/pink-mist/sbotools/pull/52

**Comment by drgibbon** [comment]
Updated for 2.6

**Comment by pink-mist** [comment]
So, these completions ... as I don't use zsh myself, I have no idea where on the filesystem these files are supposed to go for zsh to pick them up?

**Comment by drgibbon** [comment]
Putting the completion files in `/usr/share/zsh/site-functions` will work.

**Comment by drgibbon** [comment]
It's quite convenient for example to go:
```console
root@slack ~ # sbofind ffm<tab>
completing SBo SlackBuild
ffmpeg2theora      ffmpeg4            ffmpegthumbnailer  ffms2  
```
I'm guessing this can be done in bash too, but I don't know how to write those yet.

**Comment by pink-mist** [comment]
> Putting the completion files in `/usr/share/zsh/site-functions` will work.

As in `/usr/share/zsh/site-functions/_sbocheck` etc.?

**Comment by drgibbon** [comment]
> As in `/usr/share/zsh/site-functions/_sbocheck` etc.?

Like that yes (they won't get picked up in a subdirectory).

**Pull request merged**
